apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-authelia-ingress
  annotations:
    nginx.ingress.kubernetes.io/access-log: "true"
    nginx.ingress.kubernetes.io/enable-rewrite-log: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: 'true'
spec:
  tls:
    - hosts:
      - authelia.{{ .Values.baseHostname }}
      secretName: wildcard-tls-cert
  ingressClassName: "nginx"
  rules:
    - host: authelia.{{ .Values.baseHostname }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-authelia-service
                port:
                  number: 9091
