apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nextcloud-database-configmap
  labels:
    app: {{ .Release.Name }}-nextcloud-database
data:
  POSTGRES_DB: nextcloud
  POSTGRES_USER: nextcloud 
  POSTGRES_PASSWORD:  {{ .Files.Get (printf "%s/secrets/nextcloud/postgress_password" .Values.secretsPath) }}